### ISSUE TITLE
Because its a plugin, yo-yoify always runs last and I can't ES6-to-5 my code

### ISSUE THREAD

**Issue by josephg** [shama/yo-yoify#13]
I want browserify to output es5 using buble (and for that es5 code to be run through uglifyify, which still doesn't support es6).

So I want `source` -> `yo-yoify` -> `buble` -> `uglify`.

Unfortunately, because yo-yoify installs itself in a plugin, yo-yoify always runs last. So either buble eats the tagged template strings (well, [barfs on them](https://gitlab.com/Rich-Harris/buble/blob/master/src/program/types/TaggedTemplateExpression.js#L6-8) ), or I tell buble to ignore all template strings (then I get un-compiled ES6 template strings in my output and uglify doesn't work). Even if buble did support template strings, because it would run first yo-yoify would stop working.

**Comment by shama** [comment]
It could become a transform again. I was gearing it up for https://github.com/shama/yo-yoify/issues/10 but those would each likely be their own transforms anyways.

**Comment by yoshuawuyts** [comment]
So for #9 to succeed the `choo` api is going to change from `require('choo').view` to `require('choo/html')` so in that regard it shouldn't matter if it's a transform or a plugin.

**Comment by shama** [comment]
`3.0.0` turned this back into a transform and now `choo.view` and `require('choo/html')` are supported.
