### ISSUE TITLE
Support choo

### ISSUE THREAD

**Issue by yoshuawuyts** [shama/yo-yoify#14]
As per #9, it'd be rad if `yo-yoify` could modify `choo` nodes. Before this can be done, there's two issues blocking it:
- #13 - this should probably be a transform again
- https://github.com/yoshuawuyts/choo/issues/71 - choo should use `require('choo/html')`

Then we can start implementing it. Thanks! :sparkles:

**Comment by shama** [comment]
Cool. I'll keep my eye here. Working on `on-load` then will circle back to help implementing this.

**Comment by yoshuawuyts** [comment]
Yay, thanks! Def seems like the right priority :sparkles:

**Comment by shama** [comment]
`3.0.0` turned this back into a transform and now `choo.view` and `require('choo/html')` are supported.

**Comment by yoshuawuyts** [comment]
omg yes! Thanks so much :sparkles:
