### ISSUE TITLE
Path to appendChild.js doesn't resolve in Windows

### ISSUE THREAD

**Issue by nickpeihl** [shama/yo-yoify#17]
It appears [this require statement](https://github.com/shama/yo-yoify/blob/master/index.js#L228) fails to resolve the appendChild.js file correctly when using Windows. I believe this is an issue with the `path.resolve` statement and that Windows uses `\` instead of `/` as path separators. 

[Stack trace](https://gist.github.com/nickpeihl/5d01e2e0ca3bc7a76fef37697c8c5e0f). Tested on Windows 7 and Node 6.3.0.

**Comment by depoulo** [comment]
Could reproduce this issue on Windows 10 (Node 6.3.0)
