### ISSUE TITLE
Not recursively transforming ???

### ISSUE THREAD

**Issue by MattMcFarland** [shama/yo-yoify#18]
The question marks there as this appears to be the issue as the source is not changing from using `html` 

![screenshot from 2016-07-25 22 57 05](https://cloud.githubusercontent.com/assets/5105812/17089697/2c6b4484-51f7-11e6-81a1-045fa8fdccc2.png)

![screenshot from 2016-07-25 23 21 31](https://cloud.githubusercontent.com/assets/5105812/17089706/3f5cd5c6-51f7-11e6-8522-180e1c467c26.png)

The origin of the error occurs here: https://github.com/trainyard/generator-choo/issues/6  

We were able to fix our build script by removing yo-yoify: https://github.com/trainyard/generator-choo/commit/4469ee91ee808f4856d8a407839bbb3c34d0d352

**Comment by shama** [comment]
I think this line: https://github.com/trainyard/generator-choo/blob/master/app/templates/src/components/todo-list.js#L8 is the issue.

It is expecting the template string to be HTML but instead it is just an expression so it leaves it alone.

If each `todo` is already an HTML element, you don't need to wrap it in a tagged template string. Just do this instead:

``` js
module.exports = (todos = [], send) => html`
  <ul>
    ${
      todos.map(item => todo(item, () => send('todoDemo:toggle', {id: item.id})))
    }
  </ul>
`
```

**Comment by MattMcFarland** [comment]
Wow that totally fixed it.. Thanks!!! 

Man I almost think it might be nice to add a eslint plugin or something..  Or maybe have yo-yoify throw an error if it sees that?

**Comment by shama** [comment]
Yep! I agree it would be cool if yo-yoify threw an error on things like that. I'll look into it.
