### ISSUE TITLE
Can we do this with `h`?

### ISSUE THREAD

**Issue by nichoth** [shama/yo-yoify#2]
Can we do this transform with calls to `bel.createElement` or just bel`...`? Could create another transform module that takes calls to any `h` function and turns them into `document.createElement`.

**Comment by shama** [comment]
If I'm understanding your question correctly, [hyperxify](https://www.npmjs.com/package/hyperxify) does that.

**Comment by nichoth** [comment]
hyperxify transforms calls to `hyperx` into calls to an `h` module.

> If you look in the bundle.js file, you can see that the hyperx template strings have been replaced with calls to vdom.h

The `h` module would then return a virtual node or an html string depending on which you're using, so it is similar. yo-yoify takes a call to `yo` and transforms it to a DOM node, where as hyperxify takes a call to `h` and transforms it into a string.  So you could implement this in an `h` module — have it return a DOM node instead of a string.

**Comment by nichoth** [comment]
Actually, you're right, `hyperscript` and `bel` do return DOM nodes not strings, so hyperxify + hyperscript is exactly this.
