### ISSUE TITLE
`for` attribute on <label> set as `htmlFor`

### ISSUE THREAD

**Issue by seangenabe** [shama/yo-yoify#21]
The `for` attribute on `<label>` elements is set as `htmlFor` instead of `for`.

[Sample code](https://gist.github.com/seangenabe/abf8555a5e709f6fc88fda92abf1516c)

Actual: `labelElement.setAttribute("htmlFor", "abc")`
Expected: either `labelElement.htmlFor = "abc"` or `labelElement.setAttribute("for", "abc")`

**Comment by goto-bus-stop** [comment]
Not sure when this was fixed, but it's working for me in the latest release:

```js
➜ cat index.js 
const yoyoify = require('yo-yoify')
const { PassThrough } = require('stream')

let stream = new PassThrough()
stream.pipe(yoyoify()).pipe(process.stdout)
stream.end("const yo = require('yo-yo'); yo`<label for='abc'></label>`")

➜ node index.js 
const yo = require('yo-yo'); (function () {
      
      var ac = require('/tmp/node_modules/yo-yoify/lib/appendChild.js')
      var bel0 = document.createElement("label")
bel0.setAttribute("for", "abc")
      return bel0
    }())
```
