### ISSUE TITLE
Support for xlink?

### ISSUE THREAD

**Issue by kristoferjoseph** [shama/yo-yoify#27]
Does this patch need to make it into yo-yoify?
https://github.com/shama/bel/pull/31

**Comment by yoshuawuyts** [comment]
oh interesting; is it bugging out right now? - what would need to change?

**Comment by kristoferjoseph** [comment]
I am seeing the same error I saw previously using xlinks in yo-yo.
Haven't had time to debug it yet, but I figure it is a similar fix ( add createElementNS )

**Comment by kristoferjoseph** [comment]
`o.setAttributeNS(null,"xlink:href","#"+arguments[0])` 👈 This output will throw since the namespace  needs to be set to:
`http://www.w3.org/1999/xlink`
Correct output needs to be:
`o.setAttributeNS(http://www.w3.org/1999/xlink,"xlink:href","#"+arguments[0])`
Actual Error:
`Uncaught DOMException: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.`

**Comment by shama** [comment]
Dang yeah, ideally what I'd like to do is have everything handled by `bel`. Using `bel` directly, will process tagged template strings or provide an API of the operations it would make to process the template, so this transform could use that API and all that logic stays in `bel`. This would also fix potential versioning issues between developed with `bel@x` vs using `yo-yoify@x`.

**Comment by kristoferjoseph** [comment]
Are you saying that instead of outputting a setAttribute string yo-yoify would instead output a call to a bel API function?

**Comment by shama** [comment]
The output code would still contain direct calls to `el.setAttribute()` but the transform would use the version of bel the file it's transforming is using to build those statements.

So this transform, instead of copying the logic in `bel` and outputting strings, it would get an array of operations from `bel` to write to replace in the file:

``` js
const element = bel.createElement('strong', { className: 'foo' }, [ 'waddup'])
// Regular HTMLElement as we currently get: <strong class="foo">waddup</strong>

// No idea about the interface to this but we want to use the local version of bel that the file we are transforming is using
const belCreateElementOps = require(betterResolveThisPath(transformingfilepath + '/node_modules/bel/createElementOps'))
const ops = belCreateElementOps('strong', { className: 'foo' }, [ 'waddup'])
ops = [
  "var {0} = document.createElement('strong')",
  "{0}.setAttribute('class', 'foo')",
  "var {1} = document.createTextNode('waddup')",
  "{0}.appendChild({1})"
]
```

Then this transform just takes those operations, maybe optimize them as a group where we can, and produces the final output code.

**Comment by kristoferjoseph** [comment]
Any progress on this?

**Comment by yoshuawuyts** [comment]
I haven't had the bandwidth to look at this; sorry

**Comment by kristoferjoseph** [comment]
Only reason I ask is I am not able to minify my output currently due to this issue 😿 
I can work on a PR, but based off of @shama's reply I need more clarification.
Here is my understanding for how I would need to get this fix landed in the _blessed_ way:
- [ ] Add createElementOps to bel with a PR
- [ ] Make a PR that uses that method to generate the `createElement/NS` `setAttribute/NS` output strings here in yo-yoify

Does this sound correct?

**Comment by shama** [comment]
@kristoferjoseph We could add a temporary patch if needed. As the idea above is going to take some more time.

**Comment by kristoferjoseph** [comment]
OK. I can make a PR. Thank you kindly.
