### ISSUE TITLE
Incorrectly removed whitespaces

### ISSUE THREAD

**Issue by mantoni** [shama/yo-yoify#48]
As commented on PR #45, some layouts are screwed up now (I should have opened an issue in the first place). Consider this:

```html
<em>Yes</em>
<span>yo</span>
```

This should render as "Yes yo". With the change from #45 it becomes "Yesyo".

You can replace multiple whitespace characters with a single blank though. That'd be fine.

**Comment by yoshuawuyts** [comment]
potential fix https://github.com/shama/bel/pull/74

**Comment by mantoni** [comment]
So what's the solution here? The "fix" applied to bel contains a whole bunch of things and it's a bit hard to extract what is needed to fix the issue in yo-yoify. Can you help @yoshuawuyts?

**Comment by yoshuawuyts** [comment]
Gotta resolve this; it's a priority of mine rn
https://github.com/shama/bel/pull/77
