### ISSUE TITLE
Why not adding whitespace between words?

### ISSUE THREAD

**Issue by JSteunou** [shama/yo-yoify#53]
examples are like thousand words

```
const cap = require('lodash/capitalize');

bel`<p>${cap('hello')} ${cap('world')}!</p>`
```

will shout `HelloWorld!` with yo-yoify but `Hello World!` with bel

This come from https://github.com/shama/yo-yoify/blob/master/lib/appendChild.js#L15

**Comment by JSteunou** [comment]
Seems to be since https://github.com/shama/yo-yoify/pull/45

If some other people have the same issue you should stay with 3.7.2 as 3.7.3 introduced this breaking change without bumping major.

**Comment by mantoni** [comment]
For anyone coming accross this issue: I was able to use the [nanohtml](https://github.com/choojs/nanohtml) browserify transform as a drop-in replacement for `yo-yoify` and it doesn't have this issue.

**Comment by bcomnes** [comment]
Use nanohtml!  Closing.  Thanks!
