### ISSUE TITLE
Unexpected multiple tags error

### ISSUE THREAD

**Issue by seangenabe** [shama/yo-yoify#54]
The following input:
```html
<div>
  <label></label>
  <input></input>
</div>
```
unexpectedly throws:
`Error: multiple root elements must be wrapped in an enclosing tag`

**Comment by seangenabe** [comment]
Apparently, `<input>` is supposed to be self-closing. Sorry for the trouble.

**Comment by bcomnes** [comment]
lol I did the same mistake today
