### ISSUE TITLE
support for properties like `disabled` or `selected` without "=" notation

### ISSUE THREAD

**Issue by SilentCicero** [shama/yo-yoify#7]
Everytime I try to yo-yoify yo templates with properties like `disabled` or `selected` I get the error:

```
SyntaxError: Unterminated string constant (51:18)
```

example:

``` js
var yo = require("yo-yo")

function button () { 
    var disabled = "disabled"
     return yo`<button ${disabled}>Some Button</button>`
}
```

in order to make the above work I have to do something like this:

``` js
var yo = require("yo-yo")

function button () { 
    var disabled = "1"
     return yo`<button disabled=${disabled}>Some Button</button>`
}
```

@shama thoughts?

**Comment by shama** [comment]
I just hit this bug today. Currently it checks for boolean attributes by seeing if they're set to `'true'` or `'false'`. But if it's set to an expression, it can't tell.

Instead, it should detect if it's an expression and dynamically determine the boolean.

**Comment by shama** [comment]
Fixed on `3.2.2` Thanks!

**Comment by derhuerst** [comment]
I think I have this issue, with `yo-yoify@3.4.1`:

``` js
const row = (finishTodo, unfinishTodo, removeTodo) => (todo, index) => {
    const toggle = todo.finished
        ? () => unfinishTodo(index)
        : () => finishTodo(index)
    const remove = () => removeTodo(index)
    return yo `
        <li>
            <input type="checkbox"
                ${todo.finished ? 'checked' : ''}/>
        </li>`
}
```

```
Unterminated string constant (19:18)
```

**Comment by shama** [comment]
@derhuerst It might be because the lack of space on `}/>` vs `} />`. I know there is a bug in the html parser that requires that for `<br/>` vs `<br />`.

**Comment by derhuerst** [comment]
@shama

> I know there is a bug in the html parser that requires that for `<br/>` vs `<br />`.

Where can I report that issue?

**Comment by shama** [comment]
@derhuerst [hyperx](https://github.com/substack/hyperx) is the parser under the hood.
