### ISSUE TITLE
theoretical question regarding size

### ISSUE THREAD

**Issue by SilentCicero** [shama/yo-yoify#8]
Just a theoretical question here:

Thesis: yo-yoifying could actually make the app bigger vs just requiring yo dependencies.

We could assume hundreds of elements worth of transforming. This could actually end up adding size in the end. While it does make it browser friendly, it may increase size quite a bit.

Thoughts?

**Comment by shama** [comment]
Some parts of the transform could call a global injected function for common parts to reduce the file size. Performance and compatibility are more important IMO, so I'm not too worried about the file size atm. gzip is your friend.

**Comment by SilentCicero** [comment]
@shama yeah I suppose. For my use case compatibility is less an issue, more performance and total download size. Yes, gz is my friend.
